import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';

// Component integration tests run in a DOM model; they do not substitute for
// visual browser or Windows desktop verification.
test('Reset controls, preferences, and reminder use the same clock object', async () => {
  const dom = new JSDOM(await readFile(new URL('../src/index.html', import.meta.url), 'utf8'), { url: 'http://localhost:1420' });
  const { window } = dom;
  for (const key of ['window', 'document', 'localStorage', 'HTMLElement']) globalThis[key] = window[key];
  globalThis.matchMedia = () => ({ matches: false, addEventListener() {} });
  const intervals = [], timeouts = [], animationRecords = [], realInterval = globalThis.setInterval, realTimeout = globalThis.setTimeout;
  const realNow = Date.now; let now = 0; Date.now = () => now;
  globalThis.setInterval = (fn) => { intervals.push(fn); return intervals.length; };
  globalThis.setTimeout = (fn, ms) => {
    if (ms < 1000) return realTimeout(fn, 0);
    timeouts.push(fn); return timeouts.length;
  };
  window.HTMLElement.prototype.animate = function (keyframes, timing) {
    animationRecords.push({ className: this.className, keyframes, timing });
    return { finished: Promise.resolve(), cancel() {} };
  };
  window.HTMLElement.prototype.setPointerCapture = function () {};
  window.HTMLElement.prototype.hasPointerCapture = function () { return false; };
  window.HTMLElement.prototype.getBoundingClientRect = function () {
    const wide = this.classList.contains('expanded'); return { x: 100, y: 100, width: wide ? 700 : 432, height: wide ? 650 : 416, top: 100, left: 100 };
  };
  const $ = (selector) => window.document.querySelector(selector);
  const settle = () => new Promise((resolve) => realTimeout(resolve, 30));
  try {
    await import('../src/app.js'); await settle();
    assert.equal($('.button-text').textContent, 'Start focusing');
    assert.equal($('#settings-button svg').getAttribute('viewBox'), '0 0 20 20');
    assert.equal($('#settings-button svg').getAttribute('fill'), 'currentColor');
    assert.equal($('#message-choice').options.length, 12);
    assert.equal(document.querySelectorAll('.flip-card').length, 4);
    const originalClock = $('#clock');
    $('#primary-action').click(); await settle(); assert.equal($('.button-text').textContent, 'Pause focus');
    $('#primary-action').click(); await settle(); assert.equal($('.button-text').textContent, 'Resume');
    assert.equal($('#surface').classList.contains('clock-mode'), false);
    assert.equal($('.small-clock').hidden, false);
    $('#restart-action').click(); await settle();
    $('#settings-button').click(); await settle(); assert.equal($('#settings-overlay').hidden, false);
    assert.equal($('#surface').classList.contains('expanded'), false);
    assert.equal(document.body.classList.contains('settings-open'), true);
    assert.equal($('.wordmark .brand-mark'), null);
    assert.equal($('.drag-dots'), null);
    assert.equal($('#settings-timer').hidden, false); assert.equal($('#settings-appearance').hidden, true);
    $('#tab-appearance').click(); assert.equal($('#settings-timer').hidden, true); assert.equal($('#settings-appearance').hidden, false);
    $('#work-duration').value = '41';
    $('#open-help').click();
    assert.equal($('#help-view').hidden, false); assert.equal($('#settings-form').hidden, true);
    assert.equal($('.settings-tabs').hidden, true); assert.equal($('#help-faq').hidden, false);
    $('#tab-faq').dispatchEvent(new window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    assert.equal($('#help-about').hidden, false); assert.equal($('#help-faq').hidden, true);
    assert.equal($('#tab-about').getAttribute('aria-selected'), 'true');
    assert.match($('#help-about').textContent, /Hastamev/);
    $('#back-to-settings').click();
    assert.equal($('#help-view').hidden, true); assert.equal($('#settings-form').hidden, false);
    assert.equal($('#settings-appearance').hidden, false); assert.equal($('#work-duration').value, '41');
    $('#tab-appearance').dispatchEvent(new window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    assert.equal($('#settings-messages').hidden, false);
    $('#tab-timer').click();
    $('#work-options [data-minutes="45"]').click();
    $('#settings-form').elements.accent.value = 'blue';
    $('#widget-size').value = 'large';
    $('#idle-message').value = 'Stretch, breathe, and take a little pause.';
    $('#focus-message').value = 'Keep going. <b>One step at a time.</b>';
    $('#message-choice').value = '8';
    $('#message-choice').dispatchEvent(new window.Event('input', { bubbles: true }));
    assert.equal($('#message-preview').textContent, 'Rest your eyes and blink gently.');
    $('#settings-form').elements.motion.value = 'gentle';
    $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).workMinutes, 45);
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).accent, 'blue');
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).messageChoice, '8');
    assert.equal(document.documentElement.dataset.accent, 'blue');
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).widgetSize, 'large');
    assert.equal(document.documentElement.style.getPropertyValue('--widget-scale'), '1.2');
    assert.equal(document.documentElement.style.getPropertyValue('--widget-width'), '518.4px');
    assert.match($('#clock').getAttribute('aria-label'), /^Current time \d{2}:\d{2}$/);
    assert.equal($('#settings-overlay').hidden, true);
    assert.equal(document.body.classList.contains('settings-open'), false);
    assert.equal($('#surface').dataset.room, 'generous');
    assert.equal($('#widget-message-text').textContent, 'Stretch, breathe, and take a little pause.');
    $('#preview-break').click(); await settle();
    assert.equal($('#surface').classList.contains('expanded'), true);
    assert.equal($('#surface .surface-content #clock'), originalClock);
    assert.equal($('.button-text').textContent, 'Start break');
    assert.equal($('#wellness-message').textContent, 'Rest your eyes and blink gently.');
    assert.equal($('#clock'), originalClock);
    $('#postpone-action').click(); await settle();
    assert.equal($('#phase-label').textContent, 'FINISHING UP');
    assert.equal($('#surface').classList.contains('expanded'), false);
    $('#more-button').click(); assert.equal($('#more-menu').hidden, false);
    $('#more-menu [data-action="end"]').click(); await settle();
    assert.equal($('#phase-label').textContent, 'LOCAL TIME');
    $('#preview-break').click(); await settle(); $('#primary-action').click(); await settle();
    assert.equal($('#phase-label').textContent, 'BREAK'); assert.equal($('.button-text').textContent, 'Pause break');
    const beforeBreakTick = animationRecords.length;
    now += 1000; intervals[0](); await settle();
    assert.equal($('#clock').getAttribute('aria-label'), '4 minutes 59 seconds remaining');
    const breakFlips = animationRecords.slice(beforeBreakTick).filter((record) => record.className.includes('flap-'));
    assert.equal(breakFlips.length, 6);
    assert.ok(breakFlips.every((record) => record.timing.duration === 560));
    $('#skip-action').click(); await settle(); assert.equal($('#surface').classList.contains('expanded'), false);
    assert.equal($('#clock'), originalClock);
    $('#preview-theme').click(); await settle(); assert.equal(document.documentElement.dataset.theme, 'dark');
    for (const [size, scale, width] of [['small', '0.85', '367.2px'], ['medium', '1', '432px'], ['large', '1.2', '518.4px']]) {
      $('#settings-button').click(); await settle();
      $('#widget-size').value = size;
      $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
      assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).widgetSize, size);
      assert.equal(document.documentElement.style.getPropertyValue('--widget-scale'), scale);
      assert.equal(document.documentElement.style.getPropertyValue('--widget-width'), width);
      assert.equal($('#surface').classList.contains('expanded'), false);
      assert.equal($('#clock'), originalClock);
    }
    $('#settings-button').click(); await settle();
    assert.equal($('#message-choice').value, '8');
    assert.equal($('#settings-form').elements.accent.value, 'blue');
    $('#custom-message').value = 'Unplug for a moment.\n<img src=x onerror=alert(1)>';
    $('#custom-message').dispatchEvent(new window.Event('input', { bubbles: true }));
    $('#use-custom-message').click();
    assert.equal($('#message-choice').value, 'custom');
    assert.equal($('#custom-message').required, true);
    $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
    $('#preview-break').click(); await settle();
    assert.equal($('#wellness-message').textContent, 'Unplug for a moment.\n<img src=x onerror=alert(1)>');
    assert.equal($('#wellness-message').querySelector('img'), null);
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).customMessage, $('#wellness-message').textContent);
    $('#skip-action').click(); await settle();
    const resizeHandle = $('[data-corner="se"]');
    const pointer = (type, x, y) => resizeHandle.dispatchEvent(new window.MouseEvent(type, { bubbles: true, cancelable: true, button: 0, screenX: x, screenY: y }));
    pointer('pointerdown', 100, 100); pointer('pointermove', 143.2, 141.6); pointer('pointerup', 143.2, 141.6); await settle();
    const customSize = JSON.parse(localStorage.getItem('reset.preferences'));
    assert.equal(customSize.widgetSize, 'custom');
    assert.ok(Math.abs(customSize.widgetScale - 1.3) < .003);
    assert.equal($('#surface').classList.contains('resizing'), false);
    assert.equal($('#clock'), originalClock);
    pointer('pointerdown', 100, 100); pointer('pointermove', 240, 240);
    document.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await settle();
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).widgetScale, customSize.widgetScale);
    $('#settings-button').click(); await settle();
    assert.equal($('#widget-size').value, 'custom');
    $('#widget-size').value = 'medium';
    $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
    assert.equal(document.documentElement.style.getPropertyValue('--widget-scale'), '1');
    $('#settings-button').click(); await settle();
    $('#settings-form').elements.showClockSeconds.checked = true;
    $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
    assert.equal(JSON.parse(localStorage.getItem('reset.preferences')).showClockSeconds, true);
    assert.equal($('#clock').classList.contains('six-digits'), true);
    assert.equal($('#clock').querySelectorAll('.flip-card:not([hidden])').length, 6);
    assert.match($('#clock').getAttribute('aria-label'), /^Current time \d{2}:\d{2}:\d{2}$/);
    const clockFlips = animationRecords.length; now += 1000; intervals[0](); await settle();
    assert.ok(animationRecords.slice(clockFlips).some((record) => record.className.includes('flap-')));
    $('#primary-action').click(); await settle();
    assert.equal($('#clock').querySelectorAll('.flip-card:not([hidden])').length, 4);
    assert.equal($('#widget-message-text').textContent, 'Keep going. <b>One step at a time.</b>');
    assert.equal($('#widget-message-text').querySelector('b'), null);
    assert.equal($('#clock').getAttribute('aria-label'), '45 minutes 0 seconds remaining');
    $('#primary-action').click(); await settle();
    $('#settings-button').click(); await settle();
    $('#work-duration').value = '10';
    $('#settings-form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); await settle();
    assert.equal($('#clock').getAttribute('aria-label'), '10 minutes 0 seconds remaining');
    assert.equal($('.button-text').textContent, 'Resume');
    assert.match($('.small-clock').textContent, /^\d{2}:\d{2}:\d{2}$/);
    const style = document.createElement('style'); style.textContent = await readFile(new URL('../src/styles.css', import.meta.url), 'utf8'); document.head.append(style);
    assert.equal(window.getComputedStyle($('.widget-footer')).position, 'relative');
  } finally {
    globalThis.setInterval = realInterval; globalThis.setTimeout = realTimeout; Date.now = realNow; dom.window.close();
  }
});
